import type { BackendKind, HarnessCapabilities } from "./types"

export const DEFAULT_HARNESS_CAPABILITIES: Record<BackendKind, HarnessCapabilities> = {
  opencode: {
    sessions: true,
    prompt: true,
    abort: true,
    streaming: true,
    models: true,
    agents: true,
    todos: true,
    diff: true,
    filesystemBrowser: true,
    questions: true,
    permissions: true,
    commands: true,
    actions: false,
    sessionRename: true,
    sessionDelete: true,
    // Attachments reach the harness through the bridge; the OpenCode transport has no such path yet.
    attachments: false,
    // No native compact/fork endpoint outside OpenCode 2; the v1 transport has no such path yet.
    compactSession: false,
    forkSession: false
  },
  opencode2: {
    sessions: true,
    prompt: true,
    abort: true,
    streaming: true,
    models: true,
    agents: true,
    todos: false,
    diff: true,
    filesystemBrowser: true,
    questions: true,
    permissions: true,
    commands: true,
    actions: false,
    sessionRename: true,
    sessionDelete: true,
    // The v2 prompt accepts `files` attachments (base64 data URLs).
    attachments: true,
    // v2 exposes native session compaction and forking as async POST endpoints.
    compactSession: true,
    forkSession: true
  },
  omp: {
    sessions: true,
    prompt: true,
    abort: true,
    streaming: true,
    models: true,
    agents: false,
    todos: true,
    diff: false,
    filesystemBrowser: true,
    questions: false,
    permissions: false,
    commands: true,
    actions: true,
    sessionRename: true,
    sessionDelete: true,
    // Replaced by the live handshake as soon as /v1/capabilities answers.
    attachments: false,
    compactSession: false,
    forkSession: false
  },
  pi: {
    sessions: true,
    prompt: true,
    abort: true,
    streaming: true,
    models: true,
    agents: false,
    todos: false,
    diff: false,
    filesystemBrowser: true,
    questions: false,
    permissions: false,
    commands: true,
    actions: false,
    sessionRename: true,
    sessionDelete: true,
    attachments: false,
    compactSession: false,
    forkSession: false
  },
  claude: {
    sessions: true,
    prompt: true,
    abort: true,
    streaming: true,
    models: true,
    agents: false,
    todos: true,
    diff: false,
    filesystemBrowser: true,
    questions: false,
    permissions: false,
    commands: false,
    actions: false,
    sessionRename: true,
    sessionDelete: true,
    attachments: false,
    compactSession: false,
    forkSession: false
  },
  codex: {
    sessions: true,
    prompt: true,
    abort: true,
    streaming: true,
    models: true,
    agents: false,
    todos: true,
    diff: false,
    filesystemBrowser: true,
    questions: false,
    permissions: false,
    commands: true,
    actions: false,
    sessionRename: true,
    sessionDelete: true,
    attachments: false,
    compactSession: false,
    forkSession: false
  }
}
