import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const app = readFileSync(new URL('./App.tsx', import.meta.url), 'utf8')
const api = readFileSync(new URL('./api.ts', import.meta.url), 'utf8')
const i18n = readFileSync(new URL('./i18n.ts', import.meta.url), 'utf8')
const styles = readFileSync(new URL('./styles.css', import.meta.url), 'utf8')

assert.ok(api.includes('listModels(config: ServerConfig'), 'API should expose configured OpenCode models')
assert.ok(api.includes('withDirectory("/config/providers"'), 'model list should use official /config/providers with directory scoping')
assert.ok(api.includes('`/session/${sessionID}/prompt_async`'), 'chat prompts should use OpenCode async prompt endpoint')
assert.ok(api.includes('return request<boolean>(config, withDirectory(`/session/${sessionID}/prompt_async`, directory)'), 'async prompt should return after 204 instead of waiting for assistant output')
assert.ok(api.includes('model: toModelBody(model)'), 'prompt requests should send selected model object')
assert.ok(api.includes('variant: model?.variant || undefined'), 'prompt requests should preserve selected model variant')
assert.ok(api.includes('agent: agentID'), 'prompt requests should send the selected primary agent')
assert.ok(api.includes('listAgents(config: ServerConfig'), 'API should expose configured OpenCode agents')
assert.ok(api.includes('withDirectory("/agent"'), 'agent list should use official /agent endpoint with directory scoping')
assert.ok(api.includes('toCreateSessionModel'), 'new sessions should be creatable with the selected model')
assert.ok(app.includes('MODEL_STORAGE_KEY'), 'selected AI model should persist locally')
assert.ok(app.includes('AGENT_STORAGE_KEY'), 'selected plan/build agent should persist locally')
assert.ok(app.includes('modelStorageScope(backend: ServerConfig["backend"], sessionID?: string)'), 'model persistence must be scoped by backend and session')
assert.ok(app.includes('writeStoredModel(config.backend, selectedSession?.id, nextKey)'), 'model changes must persist only for the open backend session')
assert.ok(/const activeModel = activeModelOption[\s\S]*?: undefined/.test(app), 'a prompt must never send a stored model that is absent from the current backend catalog')
assert.ok(app.includes('loadModelsRequestRef'), 'stale model catalogs from another session or backend must be ignored')
assert.ok(/async function loadModels\([\s\S]*?const current = \(\) =>[\s\S]*?requestID === loadModelsRequestRef\.current/.test(app), 'only the latest model request may update the picker')
assert.match(app, /function changeModel\([\s\S]*?loadModelsRequestRef\.current \+= 1[\s\S]*?setSelectedModelKey/, 'an explicit model choice must invalidate an older model loader result')
assert.match(app, /function changeAgent\([\s\S]*?loadAgentsRequestRef\.current \+= 1[\s\S]*?setSelectedAgentID/, 'an explicit agent choice must invalidate an older agent loader result')
assert.ok(app.includes('agentOptions.filter((agent) => agent.mode === "primary" || agent.mode === "all")'), 'agent picker should expose primary agents such as build and plan')
assert.ok(app.includes('activeAgent?.id ?? "build"'), 'agent selection should default to build')
assert.ok(app.includes('id="agent-select"'), 'AI sheet should render an agent selector')
assert.ok(app.includes('attachments, isWorking ? "queue" : "steer"'), 'chat prompts should use selected agent, staged attachments, and queue follow-ups while working')
assert.ok(app.includes('sendCommandV2(config, selectedSession.id, command, args, selectedSession.directory, activeModel, activeAgentID, commandRequestID)'), 'slash commands should use selected agent')
assert.ok(app.includes('session-context-strip'), 'detail UX should expose compact mobile context chips')
assert.ok(app.includes('activeDetailSheet === "ai"'), 'model picker should open in the bottom sheet')
assert.ok(app.includes("t('detail.modelHint')"), 'model picker should explain when the change applies')
assert.match(app, /disabled=\{isWorking \|\| mutationLocked\}/, 'model picker should be disabled while running or under a mutation lock')
assert.match(app, /async function loadAgents\(sessionID = selectedSession\?\.id, directory = selectedSession\?\.directory \?\? selectedNewSessionDirectory\)/, 'agent loads must accept an explicit destination')
assert.match(app, /loadAgents\(sessionID, directory\), loadModels\(sessionID, directory\)/, 'opening a session must load both catalogs for the destination')
assert.match(app, /loadAgents\(created\.id, created\.directory\), loadModels\(created\.id, created\.directory\)/, 'creating a session must load both catalogs for the created destination')
assert.ok(app.includes('const removedSessionIDsRef = useRef(new Map<string, Set<string>>())'), 'tombstones should be retained in namespace-scoped storage')
assert.ok(app.includes('mergedSessionTombstones(removedSessionIDsRef.current, tombstoneKey, persistedTombstoneKey)'), 'session refreshes should merge tombstones for the active profile/server namespace')
assert.ok(app.includes('removedSessionIDsRef.current.set(tombstoneKey, tombstones)'), 'deletes should persist tombstones in their captured profile/server namespace')
assert.ok(!app.includes('removedSessionIDsRef.current.clear()'), 'profile/server transitions must not globally clear tombstones')
assert.ok(app.includes('REMOVED_SESSION_STORAGE_KEY'), 'tombstones need a durable storage namespace')
assert.match(app, /authoritativeIDs = new Set\(hydratedItems\.map/, 'only an authoritative list may reconcile tombstones')
// Per-session composer drafts follow the same namespace discipline as tombstones: they survive
// session-only navigation and away/back navigation within a profile/config, and are dropped only
// when the profile or config changes.
assert.ok(app.includes('sessionDraftsRef'), 'composer drafts must be preserved per session across navigation')
assert.ok(app.includes('pendingForkDraftRef'), 'an unconfirmed fork must preserve its draft snapshot for a later manual open')
assert.match(app, /sessionDraftsRef\.current\.clear\(\)[\s\S]*?pendingForkDraftRef\.current = null/, 'a profile/config transition must drop parked drafts and pending fork snapshots together')
// PR #22: a send retires the parked draft at the commit boundary, so already-sent text can never
// resurrect on a session round-trip; an empty outgoing composer deletes the stale entry instead.
assert.match(app, /function clearParkedDraft\(sessionID: string\)[\s\S]*?sessionDraftsRef\.current\.delete\(sessionDraftKey\(/, 'sends must be able to retire the session\u2019s parked draft')
assert.ok(app.includes('clearParkedDraft(selectedSession.id)') && app.includes('clearParkedDraft(session.id)'), 'prompt/command and skill sends must retire the parked draft at their commit boundary')
assert.ok(app.includes('mergedSessionTombstones'), 'runtime and hydrated tombstones must be merged instead of shadowed')
assert.match(app, /authoritativeGlobalListing[\s\S]*?if \(!refreshIsCurrent\(\)\) return true[\s\S]*?if \(authoritativeGlobalListing\)/, 'tombstones may retire only after an authoritative current refresh')
assert.ok(app.includes('modelSearchText'), 'model picker should support searching models')
assert.ok(app.includes('id="model-search"'), 'model picker should render a searchable model input')
assert.ok(app.includes("api.createSession(config, t('sessions.remoteSessionTitle'), activeModel, directory)"), 'new sessions should inherit the selected model and use a translated remote title')
assert.ok(app.includes('diffFiles.length > 0 ? t(\'detail.filesCount\''), 'details sheet should summarize file diffs only when diff data exists')
assert.ok(!app.includes('showFilesChip = diffFiles.length > 0'), 'file diff chip should stay removed from the context strip')
assert.ok(i18n.includes("'detail.contextStripLabel'"), 'context chip strings should be translated')
assert.ok(i18n.includes("'detail.modelToolsYes'"), 'model capability text should be translated')
assert.ok(i18n.includes("'detail.modelSearchPlaceholder'"), 'model search strings should be translated')
assert.ok(/\.context-chip[\s\S]*?overflow/.test(styles), 'context chips should have compact mobile styling')
assert.ok(/@media \(max-width: 780px\)[\s\S]*?\.session-context-strip\s*\{[\s\S]*?position:\s*sticky[\s\S]*?top:\s*calc\(3\.75rem \+ env\(safe-area-inset-top\)\)/.test(styles), 'mobile model and detail context should remain visible below the session app bar')
assert.ok(/\.bottom-sheet[\s\S]*?max-height/.test(styles), 'model/details should use a mobile bottom sheet')
assert.ok(/\.model-option-list[\s\S]*?overflow-y/.test(styles), 'searchable model results should scroll in the sheet')
assert.ok(/\.model-option[\s\S]*?min-height:\s*2\.75rem/.test(styles), 'model options should preserve a touch-sized minimum height')
assert.ok(/\.model-option span[\s\S]*?line-height:\s*1\.3/.test(styles), 'model option text should not look vertically squeezed')

console.log('model picker regression tests passed')
